import type { MenuItem } from "@/types";

export const menuItems: MenuItem[] = [
  {
    id: "m-101",
    name: "Paneer Tikka Wrap",
    categoryId: "cat-snacks",
    description: "Char-grilled paneer, mint chutney, pickled onions, soft rumali wrap.",
    price: 249,
    prepTime: "18 min",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=900&q=80",
    rating: 4.7,
    tags: ["Best seller", "Veg"],
    available: true,
  },
  {
    id: "m-102",
    name: "Executive Thali",
    categoryId: "cat-main",
    description: "Dal, seasonal sabzi, paneer curry, rice, roti, salad, dessert.",
    price: 389,
    prepTime: "22 min",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
    tags: ["Combo", "Lunch"],
    available: true,
  },
  {
    id: "m-103",
    name: "Masala Omelette Toast",
    categoryId: "cat-breakfast",
    description: "Three-egg omelette with toasted sourdough and herb butter.",
    price: 199,
    prepTime: "12 min",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
    rating: 4.5,
    tags: ["Breakfast"],
    available: true,
  },
  {
    id: "m-104",
    name: "Cold Coffee Float",
    categoryId: "cat-drinks",
    description: "House cold coffee with vanilla scoop and cocoa dust.",
    price: 179,
    prepTime: "8 min",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80",
    rating: 4.6,
    tags: ["Chilled"],
    available: true,
  },
  {
    id: "m-105",
    name: "Chocolate Lava Cake",
    categoryId: "cat-dessert",
    description: "Warm chocolate cake with molten center and berry compote.",
    price: 219,
    prepTime: "14 min",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80",
    rating: 4.9,
    tags: ["AI pick"],
    available: false,
  },
  {
    id: "m-106",
    name: "Hyderabadi Biryani Bowl",
    categoryId: "cat-main",
    description: "Layered dum biryani, raita, salan, fried onion garnish.",
    price: 429,
    prepTime: "26 min",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
    tags: ["Popular"],
    available: true,
  },
];
